spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: cqrs-stock
server:
    port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://servicediscovery1.com:8761/eureka
  registerWithEureka: true
  fetchRegistry: true